### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by Tereseus** [n-k-f/ColmarAcademy#3]
Your video autoplays, you should look into implementing controls for the video so that it doesn't start when the page loads. If not the video will already be done by the time you get to that part of the page. Take a look here to implement video controls in your html:

https://www.w3schools.com/tags/att_video_controls.asp

**Comment by n-k-f** [comment]
Ah, thanks for this, @Tzuridis. I did have `controls` in the original html, in fact (I think they just didn't appear unless you hovered on the video since it was already playing). And I didn't have autoplay at first but later on figured since it was a pretty plain video it'd be more fun to have it automatically playing and looping. Good point, though. I've removed autoplay and left `controls` and `loop` so it's still adjustable by the user but will keep going if the user doesn't pause it.
